version: '3'
services:
  database:
    image: "postgres"
    # environment:
    #   - POSTGRES_USER:jonp
    #   - POSTGRES_PASSWORD:jonp
    #   - POSTGRES_DB:go_rest_api
    #   - POSTGRES_HOST:database
    #   - POSTGRES_PORT:5432
    #   - POSTGRES_URL:postgres://jonp:jonp@localhost/go_rest_api?sslmode=disable

    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - go-rest-api-db:/var/lib/postgresql/data/


volumes:
  go-rest-api-db:
